/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp /home/beacon/11/OSD_Widget/IFX/mvObjIFMethodVidSig.xml -i mvobj.h -p /home/beacon/11/OSD_Widget/IFX/mvObjIFMethodVidSig
 *
 * qdbusxml2cpp is Copyright (C) 2019 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "/home/beacon/11/OSD_Widget/IFX/mvObjIFMethodVidSig.h"

/*
 * Implementation of interface class MvMvappVidsigDispInterface
 */

MvMvappVidsigDispInterface::MvMvappVidsigDispInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

MvMvappVidsigDispInterface::~MvMvappVidsigDispInterface()
{
}

/*
 * Implementation of interface class MvMvappVidsigVinInterface
 */

MvMvappVidsigVinInterface::MvMvappVidsigVinInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

MvMvappVidsigVinInterface::~MvMvappVidsigVinInterface()
{
}

/*
 * Implementation of interface class MvMvappVidsigVoutInterface
 */

MvMvappVidsigVoutInterface::MvMvappVidsigVoutInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

MvMvappVidsigVoutInterface::~MvMvappVidsigVoutInterface()
{
}

