/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp /home/beacon/11/OSD_Widget/IFX/mvObjIFMethodDisp.xml -i mvobj.h -p /home/beacon/11/OSD_Widget/IFX/mvObjIFMethodDisp
 *
 * qdbusxml2cpp is Copyright (C) 2019 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "/home/beacon/11/OSD_Widget/IFX/mvObjIFMethodDisp.h"

/*
 * Implementation of interface class MvMvappDispGrbiInterface
 */

MvMvappDispGrbiInterface::MvMvappDispGrbiInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

MvMvappDispGrbiInterface::~MvMvappDispGrbiInterface()
{
}

/*
 * Implementation of interface class MvMvappDispOsdInterface
 */

MvMvappDispOsdInterface::MvMvappDispOsdInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

MvMvappDispOsdInterface::~MvMvappDispOsdInterface()
{
}

/*
 * Implementation of interface class MvMvappDispRouterInterface
 */

MvMvappDispRouterInterface::MvMvappDispRouterInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

MvMvappDispRouterInterface::~MvMvappDispRouterInterface()
{
}

