/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp /home/beacon/Qt/OSD_Widget/IFX/mvObjIFMethodDev.xml -i mvobj.h -p /home/beacon/Qt/OSD_Widget/IFX/mvObjIFMethodDev
 *
 * qdbusxml2cpp is Copyright (C) 2019 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "mvObjIFMethodDev.h"

/*
 * Implementation of interface class MvMvappDevFansInterface
 */

MvMvappDevFansInterface::MvMvappDevFansInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

MvMvappDevFansInterface::~MvMvappDevFansInterface()
{
}

/*
 * Implementation of interface class MvMvappDevStatInterface
 */

MvMvappDevStatInterface::MvMvappDevStatInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

MvMvappDevStatInterface::~MvMvappDevStatInterface()
{
}

/*
 * Implementation of interface class MvMvappDevVerInterface
 */

MvMvappDevVerInterface::MvMvappDevVerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

MvMvappDevVerInterface::~MvMvappDevVerInterface()
{
}

